name: Page View Counter
version: 2.0.0
icon:
  name: eye
  solid: fontawesome|solid
description: Page View Counter plugin will help you to know how many readers of every page in your website.
author:
  name: Sergey Romanenko
  email: sergey.romanenko@flextype.org
  url: http://flextype.org
homepage: https://github.com/flextype-plugins/page-view-counter
bugs: https://github.com/flextype-plugins/page-view-counter/issues
license: MIT
