name: Page View Counter
version: 1.3.1
icon: fas fa-eye
description: Page View Counter plugin will help you to know how many readers of every
  page in your website.
author:
  name: Sergey Romanenko
  email: awilum@yandex.ru
  url: http://flextype.org
homepage: https://github.com/flextype-plugins/page-view-counter
bugs: https://github.com/flextype-plugins/page-view-counter/issues
license: MIT
